# Generated by Django 4.0.3 on 2022-05-18 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0015_feedbackimage_delete_information'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(blank=True, upload_to='images/users/')),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctg_hobbies', to='location.category')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_hobbies', to='customer.information')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOrFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'CheckIn'), (2, 'Favorites')])),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfs_checkins', to='location.coffeeshop')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_checkins', to='customer.information')),
            ],
        ),
    ]
