# Generated by Django 4.0.3 on 2022-06-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_coffeeshop_ids_categories'),
        ('customer', '0003_alter_information_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinorfavorite',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfs_marks', to='location.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='checkinorfavorite',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_marks', to='customer.information'),
        ),
    ]
