# Generated by Django 4.0.3 on 2022-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_checkinorfavorite_coffee_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='image_link',
            field=models.ImageField(null=True, upload_to='images/users/'),
        ),
    ]
