# Generated by Django 4.0.3 on 2022-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffershop',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
