# Generated by Django 4.0.3 on 2022-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_coffeeshop_create_at_coffeeshop_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image_link',
            field=models.ImageField(blank=True, upload_to='images/users/'),
        ),
    ]
