# Generated by Django 4.0.3 on 2022-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_coffeeshop_location_alter_coffeeshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='location',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
