# Generated by Django 4.0.3 on 2022-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_coffeeshop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='max_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='minimun_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_fake',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
