# Generated by Django 4.0.3 on 2022-05-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_coffeeshop_max_price_coffeeshop_minimun_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='total_rate',
            field=models.FloatField(null=True),
        ),
    ]
