# Generated by Django 4.0.3 on 2022-05-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_coffeeshop_total_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshopcategory',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_cfs', to='location.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='imagecoffeeshop',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs_cfs', to='location.coffeeshop'),
        ),
    ]
