# Generated by Django 4.0.3 on 2022-05-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_coffeeshopcategory_coffee_shop_and_more'),
    ]

    operations = [
    ]
