# Generated by Django 4.0.3 on 2022-05-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_remove_feedback_vote_rate__lte=5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
