# Generated by Django 4.0.3 on 2022-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_coffeeshop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='location',
            field=models.CharField(max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
