# Generated by Django 4.0.3 on 2022-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_information_birthday'),
        ('location', '0015_feedbackimage_delete_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_cfs', to='customer.information'),
        ),
    ]
