# Generated by Django 4.0.3 on 2022-05-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_alter_coffeeshop_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeshop',
            old_name='minimun_price',
            new_name='minimum_price',
        ),
    ]
