# Generated by Django 4.0.3 on 2022-05-20 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0017_rename_minimun_price_coffeeshop_minimum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_cfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
