# Generated by Django 4.0.3 on 2022-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_alter_coffeeshop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='ids_categories',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
