# Generated by Django 4.0.3 on 2022-06-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_coffeeshop_ids_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='ids_categories',
        ),
    ]
