# Generated by Django 4.0.3 on 2022-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_remove_coffeeshop_ids_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='minimum_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
